version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups: &groups
      version-updates:
        applies-to: version-updates
      security-updates:
        applies-to: security-updates
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    groups: *groups
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    groups: *groups
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups: *groups
