version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      version-updates:
        applies-to: version-updates
        dependency-type: development
      security-updates:
        applies-to: security-updates
        dependency-type: development
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    groups:
      version-updates:
        applies-to: version-updates
        dependency-type: development
      security-updates:
        applies-to: security-updates
        dependency-type: development
  - package-ecosystem: pip
    directory: "/docs"
    schedule:
      interval: weekly
    groups:
      version-updates:
        applies-to: version-updates
        dependency-type: development
      security-updates:
        applies-to: security-updates
        dependency-type: production
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    allow:
      - dependency-type: "all"
    groups:
      version-updates:
        applies-to: version-updates
        dependency-type: development
      security-updates:
        applies-to: security-updates
        dependency-type: production
